/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Image */
        post: operations["verify_image_api_v1_verify_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/v1/verify/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Internal Image */
        post: operations["verify_internal_image_api_internal_v1_verify_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Text */
        post: operations["verify_text_api_v1_verify_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/v1/verify/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Internal Text */
        post: operations["verify_internal_text_api_internal_v1_verify_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentDimensions */
        AssessmentDimensions: {
            /** Factual Status */
            factual_status: ("SUPPORTED" | "REFUTED" | "MISLEADING" | "PARTLY_TRUE" | "OUTDATED" | "UNVERIFIED" | "SATIRE" | "OPINION") | "NOT_APPLICABLE";
            /**
             * Source Authenticity
             * @enum {string}
             */
            source_authenticity: "VERIFIED" | "UNVERIFIED" | "SUSPICIOUS" | "NOT_APPLICABLE";
            /**
             * Sender Identity
             * @enum {string}
             */
            sender_identity: "VERIFIED" | "UNVERIFIED" | "IMPERSONATION_LIKELY" | "IMPERSONATION_CONFIRMED" | "NOT_APPLICABLE";
            /**
             * Channel Status
             * @enum {string}
             */
            channel_status: "VERIFIED" | "UNVERIFIED" | "SUSPICIOUS" | "MALICIOUS" | "NOT_APPLICABLE";
            /**
             * Scam Risk
             * @enum {string}
             */
            scam_risk: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN";
            /**
             * Content Authenticity
             * @enum {string}
             */
            content_authenticity: "ORIGINAL" | "ALTERED" | "SYNTHETIC" | "UNVERIFIED" | "NOT_APPLICABLE";
        };
        /** Body_verify_image_api_v1_verify_image_post */
        Body_verify_image_api_v1_verify_image_post: {
            /** Image */
            image: string;
            /**
             * Question
             * @default Apakah informasi dalam gambar ini benar dan aman ditindaklanjuti?
             */
            question: string;
            /**
             * Output Mode
             * @default STRUCTURED
             * @enum {string}
             */
            output_mode: "STRUCTURED" | "NARRATIVE" | "BOTH";
        };
        /** Body_verify_internal_image_api_internal_v1_verify_image_post */
        Body_verify_internal_image_api_internal_v1_verify_image_post: {
            /** Image */
            image: string;
            /**
             * Question
             * @default Apakah informasi dalam gambar ini benar dan aman ditindaklanjuti?
             */
            question: string;
            /**
             * Output Mode
             * @default STRUCTURED
             * @enum {string}
             */
            output_mode: "STRUCTURED" | "NARRATIVE" | "BOTH";
            /**
             * Community Evidence Json
             * @default []
             */
            community_evidence_json: string;
        };
        /** CommunityEvidenceRecord */
        CommunityEvidenceRecord: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /**
             * Record Type
             * @constant
             */
            record_type: "COMMUNITY_VERIFIED_EVIDENCE";
            /** Community Post Id */
            community_post_id: string;
            /** Case Id */
            case_id: string;
            /** Revision */
            revision: number;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @constant
             */
            status: "VERIFIED_EVIDENCE";
            /** Title */
            title: string;
            /** Verified Claim */
            verified_claim: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "SUPPORTS" | "REFUTES" | "CONTEXT";
            /** Evidence Summary */
            evidence_summary: string;
            /** Redacted Text */
            redacted_text?: string | null;
            /** Published At */
            published_at: string;
            /** Verified At */
            verified_at: string;
            /** Sources */
            sources: components["schemas"]["CommunityEvidenceSource"][];
        };
        /** CommunityEvidenceSource */
        CommunityEvidenceSource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Publisher */
            publisher?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id: string;
            /** Source Type */
            source_type: string;
            /** Publisher */
            publisher: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Published At */
            published_at: string | null;
            /** Retrieved At */
            retrieved_at: string;
            /** Excerpt */
            excerpt: string;
            /** Relevance */
            relevance: number;
            /** Authority */
            authority: number;
            /** Recency */
            recency: number;
            /**
             * Stance
             * @enum {string}
             */
            stance: "SUPPORTS" | "REFUTES" | "CONTEXT" | "UNKNOWN";
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "VERIFIED" | "REVIEWED" | "UNVERIFIED";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputSummary */
        InputSummary: {
            /**
             * Input Type
             * @enum {string}
             */
            input_type: "IMAGE" | "TEXT";
            /** Content Type */
            content_type: string;
            /** Label */
            label: string;
            /** Media Type */
            media_type: string | null;
            /** Dimensions */
            dimensions: string | null;
            /** Extraction Status */
            extraction_status: string;
            /** Excerpt */
            excerpt: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Sender Context
             * @enum {string}
             */
            sender_context: "NOT_APPLICABLE" | "UNKNOWN_NUMBER" | "KNOWN_CONTACT" | "FORWARDED" | "SOCIAL_MEDIA" | "UNKNOWN";
            /** Character Count */
            character_count: number;
            /** Urls Detected */
            urls_detected: number;
            /** Pii Types Redacted */
            pii_types_redacted: string[];
        };
        /** InternalTextVerificationRequest */
        InternalTextVerificationRequest: {
            /** Text */
            text: string;
            /**
             * Question
             * @default Apakah isi teks ini benar dan aman ditindaklanjuti?
             */
            question: string;
            /** Source Url */
            source_url?: string | null;
            /**
             * Sender Context
             * @default UNKNOWN
             * @enum {string}
             */
            sender_context: "NOT_APPLICABLE" | "UNKNOWN_NUMBER" | "KNOWN_CONTACT" | "FORWARDED" | "SOCIAL_MEDIA" | "UNKNOWN";
            page_context?: components["schemas"]["PageContext"] | null;
            /**
             * Output Mode
             * @default STRUCTURED
             * @enum {string}
             */
            output_mode: "STRUCTURED" | "NARRATIVE" | "BOTH";
            /** Community Evidence */
            community_evidence?: components["schemas"]["CommunityEvidenceRecord"][];
        };
        /** NarrativePresentation */
        NarrativePresentation: {
            /** Text */
            text: string;
            /** Summary */
            summary: string;
            /** Paragraphs */
            paragraphs: string[];
        };
        /** PageContext */
        PageContext: {
            /** Title */
            title?: string | null;
            /** Before */
            before?: string | null;
            /** After */
            after?: string | null;
        };
        /** PipelineStage */
        PipelineStage: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "COMPLETED" | "SKIPPED" | "FALLBACK";
            /** Detail */
            detail: string;
            /** Duration Ms */
            duration_ms: number;
        };
        /** RecommendedAction */
        RecommendedAction: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
        };
        /** ResponsePresentation */
        ResponsePresentation: {
            /**
             * Requested Mode
             * @enum {string}
             */
            requested_mode: "STRUCTURED" | "NARRATIVE" | "BOTH";
            /** Structured */
            structured: boolean;
            narrative: components["schemas"]["NarrativePresentation"] | null;
        };
        /** RulebookTrace */
        RulebookTrace: {
            /** Corpus Versions */
            corpus_versions: string[];
            /** Retrieval Mode */
            retrieval_mode: string;
            /** Candidate Count */
            candidate_count: number;
            /** Selected Count */
            selected_count: number;
            /** Forced Rule Ids */
            forced_rule_ids: string[];
            /** Cache Hit */
            cache_hit: boolean;
            /** Duration Ms */
            duration_ms: number;
        };
        /** SourceView */
        SourceView: {
            /** Publisher */
            publisher: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Published At */
            published_at: string | null;
        };
        /** TextVerificationRequest */
        TextVerificationRequest: {
            /** Text */
            text: string;
            /**
             * Question
             * @default Apakah isi teks ini benar dan aman ditindaklanjuti?
             */
            question: string;
            /** Source Url */
            source_url?: string | null;
            /**
             * Sender Context
             * @default UNKNOWN
             * @enum {string}
             */
            sender_context: "NOT_APPLICABLE" | "UNKNOWN_NUMBER" | "KNOWN_CONTACT" | "FORWARDED" | "SOCIAL_MEDIA" | "UNKNOWN";
            page_context?: components["schemas"]["PageContext"] | null;
            /**
             * Output Mode
             * @default STRUCTURED
             * @enum {string}
             */
            output_mode: "STRUCTURED" | "NARRATIVE" | "BOTH";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationResponse */
        VerificationResponse: {
            /** Request Id */
            request_id: string;
            /** Trace Id */
            trace_id: string;
            /**
             * Status
             * @constant
             */
            status: "COMPLETED";
            /**
             * Mode
             * @constant
             */
            mode: "LIVE";
            /** Mode Notice */
            mode_notice: string;
            input_summary: components["schemas"]["InputSummary"];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "SUPPORTED" | "REFUTED" | "MISLEADING" | "PARTLY_TRUE" | "OUTDATED" | "UNVERIFIED" | "SATIRE" | "OPINION";
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN";
            dimensions: components["schemas"]["AssessmentDimensions"];
            /** Headline */
            headline: string;
            /** Evidence Sufficiency */
            evidence_sufficiency: number;
            /** Evidence Sufficiency Label */
            evidence_sufficiency_label: string;
            /** What Checked */
            what_checked: string[];
            /** Why */
            why: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Recommended Actions */
            recommended_actions: components["schemas"]["RecommendedAction"][];
            /** Sources */
            sources: components["schemas"]["SourceView"][];
            /** Uncertainty */
            uncertainty: string;
            /** Requires Human Review */
            requires_human_review: boolean;
            /**
             * Community Status
             * @enum {string}
             */
            community_status: "NOT_REQUIRED" | "ELIGIBLE_WITH_CONSENT";
            /** Privacy Notice */
            privacy_notice: string;
            rulebook: components["schemas"]["RulebookTrace"];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStage"][];
            presentation: components["schemas"]["ResponsePresentation"];
            /** Disclaimer */
            disclaimer: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    verify_image_api_v1_verify_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_image_api_v1_verify_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_internal_image_api_internal_v1_verify_image_post: {
        parameters: {
            query?: never;
            header?: {
                "x-waspadai-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_internal_image_api_internal_v1_verify_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_text_api_v1_verify_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_internal_text_api_internal_v1_verify_text_post: {
        parameters: {
            query?: never;
            header?: {
                "x-waspadai-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalTextVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
